version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: database
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test
    restart: always
    volumes:
      - mongodata:/data/db
  
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_FILE=/app/logs/app.log
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes: 
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  mongodata: